package Species2.editor;

/*Generated by MPS */

import de.itemis.mps.editor.diagram.runtime.shape.AbstractShape;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import de.itemis.mps.editor.diagram.runtime.shape.IShapeStyle;
import java.awt.BasicStroke;

public class ReactionShape extends AbstractShape {


  public ReactionShape() {
  }




  @Override
  protected void draw(final Graphics2D graphics, final Rectangle2D bounds, IShapeStyle style) {
    graphics.setColor(DiagramColors.ReactionBackgroundColor);
    graphics.fill(bounds);

    graphics.setStroke(new BasicStroke(1.0f));
    graphics.setColor(DiagramColors.ObjectBorderColour);
    graphics.draw(bounds);

    graphics.setFont(DiagramColors.DiagramFont);
    graphics.setColor(DiagramColors.TextColor);
  }

}
