package WorldSetup.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import java.math.BigDecimal;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import Units.behavior.Distance__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Substrate_Shape_Triangular__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x51ca2b62e9a67f4fL, "WorldSetup.structure.Substrate_Shape_Triangular");

  public static final SMethod<BigDecimal> get_vertex1x_decimal_id57aaQbDEkks = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_vertex1x_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("57aaQbDEkks").build();
  public static final SMethod<String> get_vertex1x_string_id3wWy5vw2hFm = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_vertex1x_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2hFm").build();
  public static final SMethod<BigDecimal> get_vertex1y_decimal_id3wWy5vw2lIl = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_vertex1y_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2lIl").build();
  public static final SMethod<String> get_vertex1y_string_id57aaQbDElMG = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_vertex1y_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("57aaQbDElMG").build();
  public static final SMethod<BigDecimal> get_vertex2x_decimal_id3wWy5vw2w5e = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_vertex2x_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2w5e").build();
  public static final SMethod<String> get_vertex2X_string_id3wWy5vw2w5C = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_vertex2X_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2w5C").build();
  public static final SMethod<BigDecimal> get_vertex2y_decimal_id3wWy5vw2w5T = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_vertex2y_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2w5T").build();
  public static final SMethod<String> get_vertex2y_string_id3wWy5vw2w6j = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_vertex2y_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2w6j").build();
  public static final SMethod<BigDecimal> get_vertex3x_decimal_id3wWy5vw2_jP = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_vertex3x_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2_jP").build();
  public static final SMethod<String> get_vertex3x_string_id3wWy5vw2_kf = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_vertex3x_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2_kf").build();
  public static final SMethod<BigDecimal> get_vertex3y_decimal_id3wWy5vw2_kw = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_vertex3y_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2_kw").build();
  public static final SMethod<String> get_vertex3y_string_id3wWy5vw2_kU = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_vertex3y_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw2_kU").build();
  public static final SMethod<String> get_prism_depth_string_id4JVq81FgwNn = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_prism_depth_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("4JVq81FgwNn").build();
  public static final SMethod<BigDecimal> get_prism_depth_decimal_id1r0uutBHYjr = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_prism_depth_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("1r0uutBHYjr").build();
  public static final SMethod<Integer> get_prism_zlocation_gridpoints_id11q$FfsSMHt = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("get_prism_zlocation_gridpoints").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("11q$FfsSMHt").build();
  public static final SMethod<Integer> get_prism_depth_gridpoints_idfEhJG2G3wz = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("get_prism_depth_gridpoints").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("fEhJG2G3wz").build();
  public static final SMethod<BigDecimal> get_prism_zcoord_decimal_id3wWy5vw3Cyg = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_prism_zcoord_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw3Cyg").build();
  public static final SMethod<String> get_prism_zcoord_string_id3wWy5vw3KqH = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_prism_zcoord_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("3wWy5vw3KqH").build();
  public static final SMethod<BigDecimal> get_prism_upperz_decimal_id2B5sNxPo4s_ = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_prism_upperz_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("2B5sNxPo4s_").build();
  public static final SMethod<Integer> get_prism_upperz_gridpoint_id11q$FfsSLP4 = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("get_prism_upperz_gridpoint").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("11q$FfsSLP4").build();
  public static final SMethod<String> get_prism_upperz_string_id1r0uutBI3Q2 = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_prism_upperz_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("1r0uutBI3Q2").build();
  public static final SMethod<BigDecimal> get_prism_lowerz_decimal_id2B5sNxPo7PW = new SMethodBuilder<BigDecimal>(new SJavaCompoundTypeImpl(BigDecimal.class)).name("get_prism_lowerz_decimal").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("2B5sNxPo7PW").build();
  public static final SMethod<String> get_prism_lowerz_string_id1r0uutBN2EH = new SMethodBuilder<String>(new SJavaCompoundTypeImpl(String.class)).name("get_prism_lowerz_string").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("1r0uutBN2EH").build();
  public static final SMethod<Integer> get_prism_lowerz_gridpoint_id11q$FfsSUmC = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("get_prism_lowerz_gridpoint").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("11q$FfsSUmC").build();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(get_vertex1x_decimal_id57aaQbDEkks, get_vertex1x_string_id3wWy5vw2hFm, get_vertex1y_decimal_id3wWy5vw2lIl, get_vertex1y_string_id57aaQbDElMG, get_vertex2x_decimal_id3wWy5vw2w5e, get_vertex2X_string_id3wWy5vw2w5C, get_vertex2y_decimal_id3wWy5vw2w5T, get_vertex2y_string_id3wWy5vw2w6j, get_vertex3x_decimal_id3wWy5vw2_jP, get_vertex3x_string_id3wWy5vw2_kf, get_vertex3y_decimal_id3wWy5vw2_kw, get_vertex3y_string_id3wWy5vw2_kU, get_prism_depth_string_id4JVq81FgwNn, get_prism_depth_decimal_id1r0uutBHYjr, get_prism_zlocation_gridpoints_id11q$FfsSMHt, get_prism_depth_gridpoints_idfEhJG2G3wz, get_prism_zcoord_decimal_id3wWy5vw3Cyg, get_prism_zcoord_string_id3wWy5vw3KqH, get_prism_upperz_decimal_id2B5sNxPo4s_, get_prism_upperz_gridpoint_id11q$FfsSLP4, get_prism_upperz_string_id1r0uutBI3Q2, get_prism_lowerz_decimal_id2B5sNxPo7PW, get_prism_lowerz_string_id1r0uutBN2EH, get_prism_lowerz_gridpoint_id11q$FfsSUmC);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static BigDecimal get_vertex1x_decimal_id57aaQbDEkks(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_xcoord_decimal_id1r0uutBHkO6.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_1$UwXl));
  }
  /*package*/ static String get_vertex1x_string_id3wWy5vw2hFm(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_xcoord_string_id1r0uutBHkNS.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_1$UwXl));
  }
  /*package*/ static BigDecimal get_vertex1y_decimal_id3wWy5vw2lIl(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_ycoord_decimal_id1r0uutBHmwz.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_1$UwXl));
  }
  /*package*/ static String get_vertex1y_string_id57aaQbDElMG(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_ycoord_string_id1r0uutBHmwl.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_1$UwXl));
  }
  /*package*/ static BigDecimal get_vertex2x_decimal_id3wWy5vw2w5e(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_xcoord_decimal_id1r0uutBHkO6.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_2$UBKM));
  }
  /*package*/ static String get_vertex2X_string_id3wWy5vw2w5C(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_xcoord_string_id1r0uutBHkNS.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_2$UBKM));
  }
  /*package*/ static BigDecimal get_vertex2y_decimal_id3wWy5vw2w5T(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_ycoord_decimal_id1r0uutBHmwz.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_2$UBKM));
  }
  /*package*/ static String get_vertex2y_string_id3wWy5vw2w6j(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_ycoord_string_id1r0uutBHmwl.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_2$UBKM));
  }
  /*package*/ static BigDecimal get_vertex3x_decimal_id3wWy5vw2_jP(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_xcoord_decimal_id1r0uutBHkO6.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_3$UCtP));
  }
  /*package*/ static String get_vertex3x_string_id3wWy5vw2_kf(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_xcoord_string_id1r0uutBHkNS.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_3$UCtP));
  }
  /*package*/ static BigDecimal get_vertex3y_decimal_id3wWy5vw2_kw(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_ycoord_decimal_id1r0uutBHmwz.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_3$UCtP));
  }
  /*package*/ static String get_vertex3y_string_id3wWy5vw2_kU(@NotNull SNode __thisNode__) {
    return Vertex__BehaviorDescriptor.get_vertex_ycoord_string_id1r0uutBHmwl.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Vertex_3$UCtP));
  }
  /*package*/ static String get_prism_depth_string_id4JVq81FgwNn(@NotNull SNode __thisNode__) {
    return Distance__BehaviorDescriptor.get_distance_value_decimal_id3wWy5vw4PXg.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Depth$8PDk)).toString();
  }
  /*package*/ static BigDecimal get_prism_depth_decimal_id1r0uutBHYjr(@NotNull SNode __thisNode__) {
    return Distance__BehaviorDescriptor.get_distance_value_decimal_id3wWy5vw4PXg.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Depth$8PDk));
  }
  /*package*/ static int get_prism_zlocation_gridpoints_id11q$FfsSMHt(@NotNull SNode __thisNode__) {
    SNode grid = SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(__thisNode__, CONCEPTS.World_Container$fW, false, false), LINKS.grid$mgtJ);
    float scale = 0;
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(grid, PROPS.Scaling$mTyg), 0x51fc4d939a305e48L)) {
      scale = ((float) 0.5);
    } else if (SEnumOperations.isMember(SPropertyOperations.getEnum(grid, PROPS.Scaling$mTyg), 0x51fc4d939a305e4aL)) {
      scale = ((float) 1.0);
    }
    return (int) Distance__BehaviorDescriptor.get_distance_in_gridpoints_id3wWy5vw4P8z.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Z_Location$8QOp), ((float) scale));
  }
  /*package*/ static int get_prism_depth_gridpoints_idfEhJG2G3wz(@NotNull SNode __thisNode__) {
    SNode grid = SLinkOperations.getTarget(SNodeOperations.getNodeAncestor(__thisNode__, CONCEPTS.World_Container$fW, false, false), LINKS.grid$mgtJ);
    float scale = 0;
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(grid, PROPS.Scaling$mTyg), 0x51fc4d939a305e48L)) {
      scale = ((float) 0.5);
    } else if (SEnumOperations.isMember(SPropertyOperations.getEnum(grid, PROPS.Scaling$mTyg), 0x51fc4d939a305e4aL)) {
      scale = ((float) 1.0);
    }
    return (int) Distance__BehaviorDescriptor.get_distance_in_gridpoints_id3wWy5vw4P8z.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Depth$8PDk), ((float) scale));
  }
  /*package*/ static BigDecimal get_prism_zcoord_decimal_id3wWy5vw3Cyg(@NotNull SNode __thisNode__) {
    return Distance__BehaviorDescriptor.get_distance_value_decimal_id3wWy5vw4PXg.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Z_Location$8QOp));
  }
  /*package*/ static String get_prism_zcoord_string_id3wWy5vw3KqH(@NotNull SNode __thisNode__) {
    return Distance__BehaviorDescriptor.get_distance_value_decimal_id3wWy5vw4PXg.invoke(SLinkOperations.getTarget(__thisNode__, LINKS.Z_Location$8QOp)).toString();
  }
  /*package*/ static BigDecimal get_prism_upperz_decimal_id2B5sNxPo4s_(@NotNull SNode __thisNode__) {
    BigDecimal z_offset = Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_depth_decimal_id1r0uutBHYjr.invoke(__thisNode__).divide(BigDecimal.valueOf(2));
    BigDecimal z_coord = Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_zcoord_decimal_id3wWy5vw3Cyg.invoke(__thisNode__);
    return z_coord.add(z_offset);
  }
  /*package*/ static int get_prism_upperz_gridpoint_id11q$FfsSLP4(@NotNull SNode __thisNode__) {
    int z_coord = ((int) Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_zlocation_gridpoints_id11q$FfsSMHt.invoke(__thisNode__));
    int z_offset = ((int) Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_depth_gridpoints_idfEhJG2G3wz.invoke(__thisNode__)) / 2;
    return z_coord + z_offset;
  }
  /*package*/ static String get_prism_upperz_string_id1r0uutBI3Q2(@NotNull SNode __thisNode__) {
    return Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_upperz_decimal_id2B5sNxPo4s_.invoke(__thisNode__).toString();
  }
  /*package*/ static BigDecimal get_prism_lowerz_decimal_id2B5sNxPo7PW(@NotNull SNode __thisNode__) {
    BigDecimal z_offset = Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_depth_decimal_id1r0uutBHYjr.invoke(__thisNode__).divide(BigDecimal.valueOf(2));
    BigDecimal z_coord = Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_zcoord_decimal_id3wWy5vw3Cyg.invoke(__thisNode__);
    return z_coord.subtract(z_offset);
  }
  /*package*/ static String get_prism_lowerz_string_id1r0uutBN2EH(@NotNull SNode __thisNode__) {
    return Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_lowerz_decimal_id2B5sNxPo7PW.invoke(__thisNode__).toString();
  }
  /*package*/ static int get_prism_lowerz_gridpoint_id11q$FfsSUmC(@NotNull SNode __thisNode__) {
    int z_coord = ((int) Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_zlocation_gridpoints_id11q$FfsSMHt.invoke(__thisNode__));
    int z_offset = ((int) Substrate_Shape_Triangular__BehaviorDescriptor.get_prism_depth_gridpoints_idfEhJG2G3wz.invoke(__thisNode__)) / 2;
    return z_coord - z_offset;
  }

  /*package*/ Substrate_Shape_Triangular__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((BigDecimal) get_vertex1x_decimal_id57aaQbDEkks(node));
      case 1:
        return (T) ((String) get_vertex1x_string_id3wWy5vw2hFm(node));
      case 2:
        return (T) ((BigDecimal) get_vertex1y_decimal_id3wWy5vw2lIl(node));
      case 3:
        return (T) ((String) get_vertex1y_string_id57aaQbDElMG(node));
      case 4:
        return (T) ((BigDecimal) get_vertex2x_decimal_id3wWy5vw2w5e(node));
      case 5:
        return (T) ((String) get_vertex2X_string_id3wWy5vw2w5C(node));
      case 6:
        return (T) ((BigDecimal) get_vertex2y_decimal_id3wWy5vw2w5T(node));
      case 7:
        return (T) ((String) get_vertex2y_string_id3wWy5vw2w6j(node));
      case 8:
        return (T) ((BigDecimal) get_vertex3x_decimal_id3wWy5vw2_jP(node));
      case 9:
        return (T) ((String) get_vertex3x_string_id3wWy5vw2_kf(node));
      case 10:
        return (T) ((BigDecimal) get_vertex3y_decimal_id3wWy5vw2_kw(node));
      case 11:
        return (T) ((String) get_vertex3y_string_id3wWy5vw2_kU(node));
      case 12:
        return (T) ((String) get_prism_depth_string_id4JVq81FgwNn(node));
      case 13:
        return (T) ((BigDecimal) get_prism_depth_decimal_id1r0uutBHYjr(node));
      case 14:
        return (T) ((Integer) get_prism_zlocation_gridpoints_id11q$FfsSMHt(node));
      case 15:
        return (T) ((Integer) get_prism_depth_gridpoints_idfEhJG2G3wz(node));
      case 16:
        return (T) ((BigDecimal) get_prism_zcoord_decimal_id3wWy5vw3Cyg(node));
      case 17:
        return (T) ((String) get_prism_zcoord_string_id3wWy5vw3KqH(node));
      case 18:
        return (T) ((BigDecimal) get_prism_upperz_decimal_id2B5sNxPo4s_(node));
      case 19:
        return (T) ((Integer) get_prism_upperz_gridpoint_id11q$FfsSLP4(node));
      case 20:
        return (T) ((String) get_prism_upperz_string_id1r0uutBI3Q2(node));
      case 21:
        return (T) ((BigDecimal) get_prism_lowerz_decimal_id2B5sNxPo7PW(node));
      case 22:
        return (T) ((String) get_prism_lowerz_string_id1r0uutBN2EH(node));
      case 23:
        return (T) ((Integer) get_prism_lowerz_gridpoint_id11q$FfsSUmC(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink Vertex_1$UwXl = MetaAdapterFactory.getContainmentLink(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x51ca2b62e9a67f4fL, 0x51ca2b62e9a67f61L, "Vertex_1");
    /*package*/ static final SContainmentLink Vertex_2$UBKM = MetaAdapterFactory.getContainmentLink(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x51ca2b62e9a67f4fL, 0x51ca2b62e9a67f69L, "Vertex_2");
    /*package*/ static final SContainmentLink Vertex_3$UCtP = MetaAdapterFactory.getContainmentLink(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x51ca2b62e9a67f4fL, 0x51ca2b62e9a67f6cL, "Vertex_3");
    /*package*/ static final SContainmentLink Depth$8PDk = MetaAdapterFactory.getContainmentLink(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x51ca2b62e9a67f4fL, 0x383c8857e006d9cfL, "Depth");
    /*package*/ static final SContainmentLink grid$mgtJ = MetaAdapterFactory.getContainmentLink(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x73ca99e5119b19e3L, 0x73ca99e5119b19e4L, "grid");
    /*package*/ static final SContainmentLink Z_Location$8QOp = MetaAdapterFactory.getContainmentLink(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x51ca2b62e9a67f4fL, 0x383c8857e006d9d4L, "Z_Location");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept World_Container$fW = MetaAdapterFactory.getConcept(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x73ca99e5119b19e3L, "WorldSetup.structure.World_Container");
  }

  private static final class PROPS {
    /*package*/ static final SProperty Scaling$mTyg = MetaAdapterFactory.getProperty(0x276cd304748c4d5dL, 0xaad04b34e2a42cedL, 0x73ca99e5119b19e6L, 0x51fc4d939a306dc0L, "Scaling");
  }
}
