package SpeciesSetup.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SpeciesLocation extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SpeciesLocation() {
    super(0xf3f95abcaef14f78L, 0xaa77fb36d4ba916aL, 0x375d1bec6ae06404L, "SpeciesLocation", "r:2195aa8a-6524-4bf0-a55a-8f5e288eeb26(SpeciesSetup.structure)/3989375547139449860");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_LOCATION_EXTERIOR_0 = new EnumerationDescriptor.MemberDescriptor("LOCATION_EXTERIOR", "Extracellular Environment", 0x375d1bec6ae06405L, "r:2195aa8a-6524-4bf0-a55a-8f5e288eeb26(SpeciesSetup.structure)/3989375547139449861");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOCATION_MEMBRANE_0 = new EnumerationDescriptor.MemberDescriptor("LOCATION_MEMBRANE", "Membrane", 0x375d1bec6ae06406L, "r:2195aa8a-6524-4bf0-a55a-8f5e288eeb26(SpeciesSetup.structure)/3989375547139449862");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOCATION_INTERIOR_0 = new EnumerationDescriptor.MemberDescriptor("LOCATION_INTERIOR", "Cell Interior", 0x375d1bec6ae06409L, "r:2195aa8a-6524-4bf0-a55a-8f5e288eeb26(SpeciesSetup.structure)/3989375547139449865");
  private final EnumerationDescriptor.MemberDescriptor myMember_LOCATION_JUNCTION_0 = new EnumerationDescriptor.MemberDescriptor("LOCATION_JUNCTION", "Cell Junction", 0x375d1bec6ae0640dL, "r:2195aa8a-6524-4bf0-a55a-8f5e288eeb26(SpeciesSetup.structure)/3989375547139449869");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf3f95abcaef14f78L, 0xaa77fb36d4ba916aL, 0x375d1bec6ae06404L, 0x375d1bec6ae06405L, 0x375d1bec6ae06406L, 0x375d1bec6ae06409L, 0x375d1bec6ae0640dL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_LOCATION_EXTERIOR_0, myMember_LOCATION_MEMBRANE_0, myMember_LOCATION_INTERIOR_0, myMember_LOCATION_JUNCTION_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "LOCATION_EXTERIOR":
        return myMember_LOCATION_EXTERIOR_0;
      case "LOCATION_MEMBRANE":
        return myMember_LOCATION_MEMBRANE_0;
      case "LOCATION_INTERIOR":
        return myMember_LOCATION_INTERIOR_0;
      case "LOCATION_JUNCTION":
        return myMember_LOCATION_JUNCTION_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
