package org.iets3.core.expr.base.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class DefaultIdentifierConfigurator extends IdentifierConfigurator {

  @Override
  public boolean allowUmlautsInIdentifiers(SAbstractConcept concept) {
    return false;
  }

  @Override
  public boolean allowParagraphsInIdentifiers(SAbstractConcept concept) {
    return false;
  }

}
